[project]
name = "idftestproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "apache-airflow==3.0.4",
    "asyncpg>=0.30.0",
    "faker>=37.5.3",
    "kafka-python>=2.2.15",
    "psycopg2-binary>=2.9.10",
]
